export const USER_LOGIN_SUCCESS = 'USER_LOGIN_SUCCESS';
export const USER_NOT_FOUND = 'USER_NOT_FOUND';
export const AUTH_LOADING = 'AUTH_LOADING';
export const AUTH_SYSTEM_ERROR = 'AUTH_SYSTEM_ERROR';
export const COOKIE_CHECKED = 'COOKIE_CHECKED';
export const USER_LOGOUT = 'USER_LOGOUT';
export const SELECT_PRODUCT = 'SELECT_PRODUCT';
export const ADD_CART = 'ADD_CART';